apiVersion: tanzu.vmware.com/v1
kind: SpringCloudGatewayRouteConfig
metadata:
  name: ui-route-config
  namespace: my-apps
spec:
  routes:
  - predicates:
    - Path=/**
    - Method=GET
    order: 1000
    filters:
    - StripPrefix=0
    tags:
    - ui
  - predicates:
    - Path=/diningsearch/**
    - Method=GET
    filters:
    - StripPrefix=0
    ssoEnabled: true
    tags:
    - ui-secure
  service:
    uri: http://where-for-dinner-ui.my-apps
---
apiVersion: tanzu.vmware.com/v1
kind: SpringCloudGatewayMapping
metadata:
  name: ui-route-mapping
  namespace: my-apps
spec:
  gatewayRef:
    name: gateway-where-for-dinner
  routeConfigRef:
    name: ui-route-config
---
apiVersion: tanzu.vmware.com/v1
kind: SpringCloudGatewayRouteConfig
metadata:
  name: search-route-config
  namespace: my-apps
spec:
  routes:
  - predicates:
    - Path=/api/search/**
    filters:
    - TokenRelay=
    - StripPrefix=0
    - RewritePath=/api/search(?<segment>/?.*), $\{segment}
    - RemoveRequestHeader=Forwarded
    tags:
    - search-api
    tokenRelay: true
    uri: http://where-for-dinner-search.my-apps
---
apiVersion: tanzu.vmware.com/v1
kind: SpringCloudGatewayMapping
metadata:
  name: search-route-mapping
  namespace: my-apps
spec:
  gatewayRef:
    name: gateway-where-for-dinner
  routeConfigRef:
    name: search-route-config
---
apiVersion: tanzu.vmware.com/v1
kind: SpringCloudGatewayRouteConfig
metadata:
  name: availability-route-config
  namespace: my-apps
spec:
  routes:
  - predicates:
    - Path=/api/availability/**
    filters:
    - StripPrefix=0
    - RewritePath=/api/availability(?<segment>/?.*), $\{segment}
    - RemoveRequestHeader=Forwarded
    tags:
    - search-api
    tokenRelay: true
    uri: http://where-for-dinner-availability.my-apps
---
apiVersion: tanzu.vmware.com/v1
kind: SpringCloudGatewayMapping
metadata:
  name: availability-route-mapping
  namespace: my-apps
spec:
  gatewayRef:
    name: gateway-where-for-dinner
  routeConfigRef:
    name: availability-route-config
